registry:
  fileStorage:
    root: /media
    recycleBin: /media/recycleBin
  pagination:
    defaultPage: 1
    defaultPageSize: 20
    maxPageSize: 100

spring:
  messages:
    basename: i18n/messages