logging:
  level:
    org.springframework.web: info
    com.fpm.registry: trace
    org.hibernate: info

spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/registry?useSSL=false
    username: spring
    password: spring
    platform: mysql