registry:
  security:
    encoderStrength: 11
  fileStorage:
    maxFileSize: 10240
  pagination:
    defaultPage: 0
    defaultPageSize: 20
    maxPageSize: 100

spring:
  messages:
    basename: i18n/messages