registry:
  security:
    encoderStrength: 11
  fileStorage:
    root: /media
    recycleBin: /media/recycleBin
  pagination:
    defaultPage: 0
    defaultPageSize: 20
    maxPageSize: 100

spring:
  messages:
    basename: i18n/messages