registry:
  fileStorage:
    root: D:\registry\media
    recycleBin: D:\registry\media\recycleBin
    tempDirectory: D:\registry\tmp

logging:
  level:
    org.springframework.web: info
    com.fpm.registry: trace
    org.hibernate: info

spring:
  jpa:
    hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/registry?useSSL=false
    username: spring
    password: spring
    platform: mysql